const express = require('express');
const router = express.Router();
const userControll = require('../controllers/userControll');
const {check, body} =  require('express-validator/check');
const isAuth = require('../middleware/is-auth');


router.get('/', userControll.getLanding);
router.get('/profile', isAuth,  userControll.getMainPage);
router.get('/edit-user/:id', isAuth, userControll.getEditUser);
router.get('/teams-page', isAuth, userControll.getTeamsPage);
router.get('/add-team', isAuth, userControll.getAddTeamPage);
router.get('/users-list', isAuth, userControll.getListOfUsers);
router.get('/user-details/:id', isAuth, userControll.getUserDetails);
router.get('/team-details/:id', isAuth, userControll.getTeamDetails);
router.get('/edit-team/:id', isAuth, userControll.getEditTeam);
router.get('/team-requests', isAuth, userControll.getRequestsPage);
router.get('/admins-list', isAuth, userControll.getAdmins);
// router.get('/invitation', isAuth, userControll.getInvitation);
router.get('/mentors', isAuth, userControll.getMentors);

router.post('/mentor-accept', isAuth, userControll.postMentorAccept);
router.post('/mentor-canclereq', isAuth, userControll.postMentorCancleRequest);
router.post('/delete-mentreq', isAuth, userControll.postMentorDeleteRequest);
router.post('/decline-all', isAuth, userControll.declineAllRequests);
router.post('/invite-teammate', isAuth, userControll.postInviteTeammate);
router.post('/admindel-member', isAuth, userControll.adminDeleteMember);
router.post('/adminDecline-member', isAuth, userControll.adminDeclineMember);
router.post('/adminAccept-member', isAuth, userControll.adminAcceptMember);
router.post('/delete-admin', isAuth, userControll.postDeleteAdmin);
router.post('/add-admin', isAuth, userControll.postAddAmin);
router.post('/delete-team', isAuth, userControll.postDeleteTeam);
router.post('/edit-team', isAuth, userControll.postEditTeam);
router.post('/signup', userControll.postSignUp);
router.post('/edit-user', isAuth, userControll.postEditUser);
router.post('/add-team', isAuth, userControll.postAddTeam);
router.post('/teammate-request', isAuth, userControll.postAddRequest);
router.post('/teammate-cancellation', isAuth, userControll.postCancelRequest);
router.post('/accept-teammate',isAuth, userControll.postAcceptRequest);
router.post('/reject-user/:teamMateId', isAuth, userControll.denyRequest);
router.post('/mentor-request', isAuth, userControll.postMentorRequest);
// router.post('/accept-invitation', isAuth, userControll.postAcceptInvitation);
// router.post('/cancel-invitation', isAuth, userControll.postCancelInvitation);
// router.post('/cancel-all-invintation', isAuth,userControll.postCancelAllInvintation);
module.exports = router;